### ISSUE TITLE
BUG for decoding in "pointer_eval" function

### ISSUE THREAD

**Issue by WitcherLeo** [steven640pixel/nonautoregressive-sentence-ordering#1]
In "pointer_eval" function of modeling_bert.py file, the decoding process can proceed successfully only when "per_gpu_eval_batch_size" is set to 1, because corresponding codes of "greedy selective and removing strategy" mentioned in the paper are designed just for eval_batch_size 1 (the last part of function pointer_eval can only choose one best_p for a single sample, if eval_batch_size > 1, the decoding process fails to proceed). So this hinders decoding and prediction at a faster speed （can not set bigger per_gpu_eval_batch_size except 1）

**Comment by steven640pixel** [comment]
Dear WitcherLeo,
  Thank you for your interest in our work;
  During inference, we refer to the open-source codes of the previous generation-based methods for sentence ordering. We simply set batch size to 1 in evaluation to facilitate fair comparison.

Best regards,
Wenhao
